// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: execstream.proto

package execstreamapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExecStreamServiceClient is the client API for ExecStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecStreamServiceClient interface {
	// StreamExec establishes a bidirectional stream for a pod exec session.
	// The client (agent) sends stdin data and receives stdout/stderr data.
	// The server (principal) receives stdin from the browser and sends stdout/stderr back.
	StreamExec(ctx context.Context, opts ...grpc.CallOption) (ExecStreamService_StreamExecClient, error)
}

type execStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecStreamServiceClient(cc grpc.ClientConnInterface) ExecStreamServiceClient {
	return &execStreamServiceClient{cc}
}

func (c *execStreamServiceClient) StreamExec(ctx context.Context, opts ...grpc.CallOption) (ExecStreamService_StreamExecClient, error) {
	stream, err := c.cc.NewStream(ctx, &ExecStreamService_ServiceDesc.Streams[0], "/execstreamapi.ExecStreamService/StreamExec", opts...)
	if err != nil {
		return nil, err
	}
	x := &execStreamServiceStreamExecClient{stream}
	return x, nil
}

type ExecStreamService_StreamExecClient interface {
	Send(*ExecStreamData) error
	Recv() (*ExecStreamData, error)
	grpc.ClientStream
}

type execStreamServiceStreamExecClient struct {
	grpc.ClientStream
}

func (x *execStreamServiceStreamExecClient) Send(m *ExecStreamData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *execStreamServiceStreamExecClient) Recv() (*ExecStreamData, error) {
	m := new(ExecStreamData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExecStreamServiceServer is the server API for ExecStreamService service.
// All implementations must embed UnimplementedExecStreamServiceServer
// for forward compatibility
type ExecStreamServiceServer interface {
	// StreamExec establishes a bidirectional stream for a pod exec session.
	// The client (agent) sends stdin data and receives stdout/stderr data.
	// The server (principal) receives stdin from the browser and sends stdout/stderr back.
	StreamExec(ExecStreamService_StreamExecServer) error
	mustEmbedUnimplementedExecStreamServiceServer()
}

// UnimplementedExecStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExecStreamServiceServer struct {
}

func (UnimplementedExecStreamServiceServer) StreamExec(ExecStreamService_StreamExecServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamExec not implemented")
}
func (UnimplementedExecStreamServiceServer) mustEmbedUnimplementedExecStreamServiceServer() {}

// UnsafeExecStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecStreamServiceServer will
// result in compilation errors.
type UnsafeExecStreamServiceServer interface {
	mustEmbedUnimplementedExecStreamServiceServer()
}

func RegisterExecStreamServiceServer(s grpc.ServiceRegistrar, srv ExecStreamServiceServer) {
	s.RegisterService(&ExecStreamService_ServiceDesc, srv)
}

func _ExecStreamService_StreamExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecStreamServiceServer).StreamExec(&execStreamServiceStreamExecServer{stream})
}

type ExecStreamService_StreamExecServer interface {
	Send(*ExecStreamData) error
	Recv() (*ExecStreamData, error)
	grpc.ServerStream
}

type execStreamServiceStreamExecServer struct {
	grpc.ServerStream
}

func (x *execStreamServiceStreamExecServer) Send(m *ExecStreamData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *execStreamServiceStreamExecServer) Recv() (*ExecStreamData, error) {
	m := new(ExecStreamData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExecStreamService_ServiceDesc is the grpc.ServiceDesc for ExecStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execstreamapi.ExecStreamService",
	HandlerType: (*ExecStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExec",
			Handler:       _ExecStreamService_StreamExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "execstream.proto",
}
